@2、createTables.sql
@3、createIndexs.sql
@4、createViews.sql
@5、createProcedures.sql
@6、initModuleAndRole.sql
@7、initDataDictionary.sql
@8、initOthers.sql
@9、createSequences.sql
@10、createTriggers.sql
exit